Поддержка запроса генерации QR-кода для оплаты через СБП
voronkovich/sberbank-acquiring-client pull request #24
Opened 2022-02-02 12:38 UTC by daniser

На данный момент функционал поддерживается только Альфа-банком.

Документация:
https://pay.alfabank.ru/ecommerce/instructions/SBP_C2B.pdf

2022-02-02 14:23 UTC, voronkovich requested changes
@daniser, благодарю за PR. Я добавил несколько замечаний.

2022-02-02 14:23 UTC, voronkovich commented on src/Client.php
> +    public function getDynamicQr($orderId, int $qrHeight = null, int $qrWidth = null, string $qrFormat = null, array $data = []): array
Предлагаю переименовать в `getSbpDynamicQr` (`dynamic` правда непонятно о чём говорит, в документации об этом ничего не сказано :( )

2022-02-02 14:23 UTC, voronkovich commented on src/Client.php
> +    public function getQrStatus($orderId, string $qrId, array $data = []): array
Здесь тоже предлагаю добавить префикс `Sbp`:

```php
public function getSbpQrStatus($orderId, string $qrId, array $data = []): array;
```

2022-02-02 15:45 UTC, daniser commented on src/Client.php
> +            'prefixQr',
Вот тут небольшая дилемма. Эндпоинты имеют вид `/payment/rest/sbp/c2b/qr/status.do`. Сейчас префикс указывается так - `/payment/rest/sbp/c2b/qr/`, т.е. делается акцент на способ оплаты посредством QR-кода.
Вижу 3 варианта решения проблемы:
1. оставить префикс как есть, опцию назвать `prefixSbpQr`.
2. префикс указывать без `qr`, т.е. `/payment/rest/sbp/c2b/`; опцию назвать `prefixSbp`.
3. использовать дефолтный префикс $prefixDefault, остальные участки пути захардкодить: `$this->execute($this->prefixDefault . 'sbp/c2b/qr/status.do')`. Не очень future-proof.
Склоняюсь к первому варианту, хотя у третьего есть свой плюс - исключение при отсутствии префикса можно не кидать, при отсутствии эндпоинта автоматически выкинется BadResponseException.
Хотелось бы услышать вашу позицию.

2022-02-02 15:50 UTC, daniser commented on src/Client.php
> +    public function getDynamicQr($orderId, int $qrHeight = null, int $qrWidth = null, string $qrFormat = null, array $data = []): array
Согласен. Зато там написано про некий `qrType` `STATIC`, который в данный момент не используется. На всякий случай предлагаю оставить `Dynamic`.

2022-02-02 16:13 UTC, daniser commented on src/Client.php
> +            'prefixQr',
Кстати, я тут подумал, в принципе по дефолту `prefixSbpQr` можно инициализировать так:
```php
$this->prefixSbpQr = $options['prefixSbpQr'] ?? self::API_PREFIX_DEFAULT . 'sbp/c2b/qr/';
```
... тем самым избегая значения `null` и лишних проверок.

2022-02-02 17:18 UTC, voronkovich commented on src/Client.php
> +            'prefixQr',
@daniser, Хорошо, пусть будет `prefixSbpQr`. Полагаю, так будет безопаснее.

2022-02-02 17:20 UTC, voronkovich commented on src/Client.php
> +            'prefixQr',
>  Кстати, я тут подумал, в принципе по дефолту prefixSbpQr можно инициализировать так:
> $this->prefixSbpQr = $options['prefixSbpQr'] ?? self::API_PREFIX_DEFAULT . 'sbp/c2b/qr/';
> ... тем самым избегая значения null и лишних проверок.

Лучше пусть останется как есть. Так пользователи библиотеки увидят исключение о том что не указан `prefixSbpQr`. Ещё не известно, сколько времени Сбербанк эту фичу будет у себя добавлять.

2022-02-02 17:21 UTC, voronkovich commented on src/Client.php
> +    public function getDynamicQr($orderId, int $qrHeight = null, int $qrWidth = null, string $qrFormat = null, array $data = []): array
Ok, пусть будет `getSbpDynamicQr`

2022-02-02 19:35 UTC, daniser commented
Доки также обновил для отражения нового функционала.

2022-02-04 14:09 UTC, voronkovich approved these changes

2022-02-04 14:10 UTC, merged

2022-02-04 14:12 UTC, voronkovich commented
@daniser, спасибо за PR!